"""empty message

Revision ID: 029050882048
Revises: d32240d6ced4
Create Date: 2026-03-15 15:11:11.679530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '029050882048'
down_revision = 'd32240d6ced4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_enrollments',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'course_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=8), nullable=False),
    sa.Column('grade', sa.Float(), nullable=True),
    sa.CheckConstraint('grade >= 0 AND grade <= 100', name='check_grade_range'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('course_enrollments')
    # ### end Alembic commands ###
