"""empty message

Revision ID: 73cdc8e98a33
Revises: 
Create Date: 2026-02-26 16:03:07.795360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73cdc8e98a33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor', sa.String(length=50), nullable=False),
    sa.Column('verb_id', sa.String(length=256), nullable=False),
    sa.Column('verb_name', sa.String(length=50), nullable=False),
    sa.Column('object', sa.JSON(), nullable=False),
    sa.Column('context', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    # ### end Alembic commands ###
