"""fix user_code length

Revision ID: d32240d6ced4
Revises: 6c70aca75fe3
Create Date: 2026-03-13 22:02:24.025151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd32240d6ced4'
down_revision = '6c70aca75fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    schema_name = "flaskmvc" if not is_sqlite else None
    
    with op.batch_alter_table('users', schema=schema_name) as batch_op:
        batch_op.alter_column('user_code',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    is_sqlite = bind.dialect.name == 'sqlite'
    schema_name = "flaskmvc" if not is_sqlite else None
    
    with op.batch_alter_table('users', schema=schema_name) as batch_op:
        batch_op.alter_column('user_code',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###
